FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./client/package*.json ./client/
COPY ./shared/package*.json ./shared/

RUN npm ci -w client

COPY ./client ./client
COPY ./shared ./shared
ARG REACT_APP_BASE_URL
ENV APP_BASE_URL=${REACT_APP_BASE_URL}

RUN npm run build -w frontend
EXPOSE 3000

CMD [ "npx", "serve", "frontend/build" ]